In [ ]:
import numpy as np

arra=np.array([1,2,3,4,5])
arrb=np.array([2,3,4,5,6])

print(arra)
print(arrb)

print(type(arra))

print(type(arrb))

print(np.arange(1,3,0.1))    #starting value of array , ending value of array i.e. if 3 then it will take one value before it , step size

print(np.arange(25))

print(np.linspace(1,5, 10))   #prints the array from first to last value and the third number will divide the array in equal values


[1 2 3 4 5]
[2 3 4 5 6]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3,4)   #first value rows and second no. of columns

#3 ==> rows,dimension,columns


print(newarr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr1=[1,2,3,4]
arr2=[5,6,7,8]
arr3=np.concatenate((arr1,arr2))
print(arr3)


arr4=[[1,2],[3,4],[5,6],[7,8]]
print(arr4)
arr5=[[11,12] ,[13,14] ,[15,16] ,[17,18]]
print(arr5)

arr6=np.concatenate((arr4,arr5),axis=1)
print(arr6)

[1 2 3 4 5 6 7 8]
[[1, 2], [3, 4], [5, 6], [7, 8]]
[[11, 12], [13, 14], [15, 16], [17, 18]]
[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]
 [ 7  8 17 18]]


In [ ]:
arr1=np.zeros((3,4))
print("zero matrix")

print(arr1)

arr2=np.ones((3,3))
print("ones matrix")
print(arr2)
arr3=np.identity((3))
print("identity matrix")
print(arr3)


zero matrix
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones matrix
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a =np.array([1,2,2,6,14,8,9,2,3])
print(a)

print(a[a>5])
print(a[a%2==0])


print(a[(a>5) & (a%2==0)])
print(np.where(a[(a>5) & (a%2==0)]))

[ 1  2  2  6 14  8  9  2  3]
[ 6 14  8  9]
[ 2  2  6 14  8  2]
[ 6 14  8]
(array([0, 1, 2]),)


In [3]:
import numpy as np
array=np.random.randint(20, size=(2,3))
print(array)

[[9 3 4]
 [1 2 4]]
